// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Jürgen Enge",
            "url": "https://info-age.ch",
            "email": "juergen@info-age.ch"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/json/{query}": {
            "get": {
                "description": "based on a GPT chat query, similar documents are searched and returned as context",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GND"
                ],
                "summary": "gets GPT query context to query",
                "operationId": "get-context-by-query-json",
                "parameters": [
                    {
                        "type": "string",
                        "description": "chat query",
                        "name": "query",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/revcatgtpservice.HTTPJSONResultMessage"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/revcatgtpservice.HTTPResultMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/revcatgtpservice.HTTPResultMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/revcatgtpservice.HTTPResultMessage"
                        }
                    }
                }
            }
        },
        "/{query}": {
            "get": {
                "description": "based on a GPT chat query, similar documents are searched and returned as context",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "GND"
                ],
                "summary": "gets GPT query context to query",
                "operationId": "get-context-by-query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "chat query",
                        "name": "query",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/revcatgtpservice.HTTPResultMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/revcatgtpservice.HTTPResultMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/revcatgtpservice.HTTPResultMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "revcatgtpservice.HTTPJSONResultMessage": {
            "type": "object",
            "properties": {
                "abstract": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "place": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "revcatgtpservice.HTTPResultMessage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "RevcatGPT API",
	Description:      "Custom GPT Metadata for Revcat",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
